# (PART) Conclusion {-}

# General discussion

This dissertation investigated the influence of consonant voicing on vowel duration by focussing on production aspects of vowel-consonant sequences.
As a cross-linguistic tendency, vowels are shorter when followed by voiceless consonants and longer when followed by voiced ones.
Several proposals as to what mechanisms underly this tendency have been proposed, but no account has won consensus.
Two studies were carried out to investigate durational and articulatory properties of vowels and consonants in Italian, Polish, and English.
Five papers presented and discussed the results from these studies.
Paper I and [...] show that the duration of the interval between the releases of the stops of a disyllabic word is not affected by the voicing of the second stop in Italian, Polish, and English.
On the other hand, the release-to-release interval of English monosyllabic words is longer when the second consonant is voiced.
The results in Paper [...] suggest the existence of a statistical correlation between vowel duration and degree of tongue root advancement, such that longer vowel durations correspond to greater tongue root advancement.
Finally, in Paper [...] it was speculated that the timing of the stop closure is modulated by the presence of emerging voiceless pre-aspiration, so that either enhancement of pre-aspiration delays closure or its prevention anticipates it.
This chapter provides an over-arching synthesis of the account proposed here in light of the observed patterns, and discusses the implications for theories of speech production.

## Gestural phasing

As argued in Paper [...], the temporal stability of the release-to-release interval is compatible with hypotheses about the gestural organisation of vowel and consonants within the domains of the syllable and the word.
According to the coupled oscillators model \citep{odell2008}, embedded in the task-dynamic model of Articulatory Phonology \citep{ohala1986a, browman1988, browman2000, goldstein2006, goldstein2014}, speech gestures can be implemented according to two coupling modes: in-phase (synchronous) or anti-phase (sequential) mode.
When two or more gestures are in an in-phase relation, they are initiated in synchrony.
If two or more gestures follow an anti-phase coupling mode, the gestures are implemented sequentially and one gesture starts when the preceding one has reached its target.
These two coupling modes can account for temporal aspects observed in the relative phasing of coda and onsets consonants with vowels.

<!-- TODO: cite Pouplier universal chapter -->
\citet{marin2010} showed that onset consonants in American English are in-phase with respect to the vowel nucleus and anti-phase with each other.
Such phasing pattern establishes a stable relationship between the centre of the consonant (or consonants in a cluster) and the following vowel.
Independent of the number of onset consonants, the temporal midpoint of the onset consonant(s) (the so-called 'C-centre') is maintained at a fixed distance from the vowel, such that an increasing number of consonants in the onset does not change the distance between the vowel and the onset C-centre (\Cref{f:gorganisation}a).
On the other hand, coda consonants are in an anti-phase relation with the preceding vowel and between themselves.
When consonants are added to the coda, they are sequentially realised.
Temporal stability in codas is found in the lag between the vowel and the left-most edge of the coda, which is not affected by the number of coda consonants (\Cref{f:gorganisation}b).
Other studies found further evidence for the synchronous and sequential coupling modes (see extensive review in \citealt{marin2010} and \citealt{marin2014}), although the use of one mode over the other depends on the language and the consonants under study [...].
Consonants can thus be said to follow either a C-centre or a left-edge organisation pattern depending on whether they are in-phase or anti-phase with the vocalic gesture.

Phasing modes are defined within the traditional syllable, or, in other words, relative to the tautosyllabic vowel (the following vowel for onsets and the preceding vowel for codas).
Less is known about the relation between heterosyllabic segments and how syllables are timed and phased within words.
\citet{ohman1967} and \citet{fowler1983} propose that vocalic gestures are implemented according to a rhythmic programme and that consonantal (constriction gestures) are superimposed to the vocalic gestural stream.
Furthermore, the authors argue that the timing of vocalic gestures follows a regular cyclic pattern, which is in turn responsible for the rhythmic patterns of speech.
\citet{fowler1983} reviews a collection of findings from speech production, perception, and phonological studies that support the idea of the cyclic production of vowels.

A consequence of the cyclic production of vowels and the independence of the vocalic and consonantal gestures is that two consecutive vowels within a word would be at a stable temporal distance independent of the nature and number of the intervening consonants.
This hypothesis, however, is not borne out by the empirical evidence in \citet{zmarich2011} and \citet{zeroual2015}.
Using electromagnetic articulography, both studies find that the distance between two vowels is greater when the intervening consonant is a geminate compared to when it is a singleton consonant.
\citet{de-jong1991} finds only partial support for the independence of vowels and consonants.
These studies also find substantial inter-speaker variation in the particulars of the gestural implementation of vowel-consonant sequences.

While the strong prediction of vowel-to-vowel isochrony is not confirmed by data comparing singleton and geminates, it is possible that a softer formulation would still work.
A possible reason for why the isochrony breaks in that context is that the geminate consonant is a blend of two phasing patterns.
For example, \citet{zeroual2015} argue that their findings support the interpretation of geminates as two identical consonants produced sequentially.
This would mean that the first part of the geminate is implemented anti-phase with the preceding vowel, while the second part is articulated in-phase with the following.
The presence of an anti-phase gesture intervening between the vowels could be responsible for the disruption of the vowel-to-vowel isochrony.
If this is the case, then isochrony would apply only in those cases where the intervening consonants are in-phase with the second vowel (a more detailed account and an alternative account are discussed in [...]).

Turning to the voicing contrast, since CVCV words differing in the voicing of C2 just include a singleton consonant, we can expect VV isochrony to apply.
Since onset consonants are in-phase with the tautosyllabic vowel and the timing of the release of C2 is not affected by voicing, the timing of the gestural onset of voiceless and voiced stops should also be identical.
<!-- TODO: schematics -->
This is in part confirmed by the ultrasound tongue imaging data of Study I.
<!-- TODO: GONS appendix -->
The duration of the interval between the acoustic release of C1 and the gestural onset time of C2 is not affected by the voicing status of C2.
On the other hand, the velocity of the closing gesture is known to differ \citep{van-summers1987}.
<!-- TODO: say that velocity data are not good here? -->
While the gestural onset is identical, the difference in closing velocity produces the acoustic pattern of the differential in VC boundary timing.
Fast closing velocity in voiceless stops creates an early VC boundary, while a slow closing gesture generates a late VC boundary.

On the other hand, in tautosyllabic VC sequences, the consonant gesture is implemented anti-phase with the preceding vowel, meaning that the gestures are produced sequentially.
In such case, VV isochrony is broken and the duration of V1 can be modulated freely.
This is what it is argued to happen in monosyllabic words, where the distance between the releases of C1 and C2 differs depending on the voicing of C2.
\citet{de-jong2002} indeed finds that in English monosyllabic words not only the velocity of the closing gesture differs, but also the timing of the consonant gesture, which happens later within the vowel in the context of voiced stops.

## One account to rule them all





# (PART) Appendices {-}
