---
title: "PhD dissertation"
author: "Stefano Coretta"
documentclass: book
---

# (PART) Background {-}

# Introduction

This is the introduction of the dissertation.

## The voicing effect and beyond

<!-- I talk mostly about stops, so maybe I have to clarify this -->
A long-recognised property of vowels is that their duration is influenced by the voicing of the consonant following them.
Across a wide variety of languages, vowels tend to be shorter when followed by voiceless consonants, and longer when followed by voiced ones.
This tendency has been called the 'voicing effect' \citep{mitleb1982}.
Remarkably, as far as we can tell, no language has been reported having the opposite effect, namely longer vowel durations before voiceless than before voiced consonants.
Possibly, the voicing effect is one of the most robust effects found in the phonetic literature (together with, for example, the effect of vowel height).
Among the earliest traceable mentions to the voicing effect there are \citet{meyer1903} for English (cited in \citealt{lindblom1967}), \citet{meyer1904} for German, \citet{meyer1909} for Hungarian, and \citet{gregoire1911} for French (all cited in \citealt{maddieson1976}).
After these, a plethora of studies confirmed the effect in these languages and reported it in other ones.

<!-- I need to talk about what I mean by voicing -->

English is by far the language that received the most attention (\citealt{heffner1937, house1953, lisker1957, zimmerman1958, peterson1960, house1961, sharf1962, sharf1964, lindblom1967, halle1967, halle1967a, slis1969a, slis1969, chen1970, klatt1973, lisker1974, raphael1975, umeda1975, javkin1976, port1982, mack1982, luce1985, van-summers1987, kluender1988, de-jong1991, laeufer1992, fowler1992, de-jong2004, warren2005, ko2018, glewwe2018, sanker2019}, among others).
The existence of the voicing effect has been further corroborated in French by \citet{belasco1953}, \citet{chen1970}, and \citet{laeufer1992}, in Hungarian by \citet{soskuthy2013}, and German (in the context of word-final voicing neutralisation, see \citealt{nicenboim2018a} and references therein).
Other voicing-effect languages are Arabic (\citealt{hussein1994}, but cf. \citealt{mitleb1982}), Assamese, Bengali, Dutch, Georgian \citep{begus2017}, Hindi \citet{maddieson1976, ohala1992a, lampp2004, durvasula2012, sanker2018}, Italian \citep{caldognetto1979, farnetani1986, esposito2002}, Icelandic, Japanese \citep{port1987}, Korean, Lithuanian, Norwegian, Swedish, Spanish, Telugu \citep{sanker2018}, and Russian [add references].
From a typological perspective, the sample is thus strongly biased towards Indo-European languages.
<!-- Maybe say this later or in footnote because it could give the impression that I will sort this out. -->
Moreover, the five non-Indo-European languages are well-studied languages.
It will thus be vital, in the future, to investigate the voicing effect in underdescribed and underdocumented languages, from a wider variety of linguistic families and geographical locations.
This notwithstanding, the voicing effect is generally regarded as a very common and widespread phenomenon.

While the existence of the voicing effect is unquestionable, a commonly shared stance is that it is not an absolute universal, and that the magnitude of the effect varies across languages that have it.
Czech and Polish are generally reputed to be languages in which the duration of the vowel does not significantly differ before voiceless and voiced stops.
In fact, the results concerning the effect in these languages suggest both absence and presence of voicing-induced vowel duration differences.
\citet{keating1984} examined the duration of vowels in 3 Czech speakers.
Vowels are 193.7 ms long when followed by /t/ and 204.2 ms when followed by /d/.
This corresponds to a raw difference of 10.5 ms, which the author reports not to be significant (*t*(30) = -0.37, p > 0.2).
Given the low number of speakers and the relative high standard error of the effect (about 28 ms, calculated as the mean difference over the *t*-value, \citealt{nicenboim2018a}), it is possible that the null result is due to low statistical power.
\citet{machac2007} analyse 638 VCV sequences recorded from 53 speakers of Czech and found partial evidence for an effect of voicing in the language.

<!-- be sure you explain contexts of V -->
As for Polish, \citet{slowiaczek1985} measured the duration of vowels in word-final syllables from 5 speakers, and vowels followed by an underlyingly voiced stop are 10--15 ms longer.
@nowak2006 investigates several properties of vowel duration in 4 speakers, and finds that vowels followed by voiced stops in 4 speakers (from different parts of Poland) are 4.5 ms longer (a significant difference).
<!-- I should read about what stats he did -->
@malisz2008 analyse data from 40 speakers of 'Standard Polish', and while they don't report estimates from the whole dataset, the means from 4 speakers suggest a difference in vowel duration before voiceless vs. voiced stops of about 3.5 ms.
On the other hand, an equal number of studies argue that voicing does not significantly affect vowel duration.
\citet{jassem1989} could not replicate the results in \citet{slowiaczek1985}.
\citet{keating1984} reports a non-significant difference of 2 ms in the word pair /rata/ (167.4) and /rada/ (169.5 ms), based on data from 24 speakers in Wrocław, Poland.
Finally, \citet{strycharczuk2012a} reports a non-significant effect in 6 speakers in pre-sonorant word-final position.
<!-- find where speakers are from -->
To summarise, the evidence concerning the presence or absence of the voicing effect in Czech and Polish is mixed and it is not possible to draw certain conclusions.
<!-- maybe add a footnote about meta-analysis -->

The second common stance about the voicing effect is that its magnitude differs across languages, and that English generally shows the greatest effect.
The latter statement led to the idea that the voicing effect is phonologised in English \citet{sole2007, sanker2018}.
The argument for the phonologisation of the effect rests, among other things, on the alleged stability of the ratio of the effect across speaking rates and prosodic contexts differing in strength.
\citet{port1982} suggest that the ratio of the consonant and vowel durations is stable at faster and slower speaking tempos, and that the CV ratio proves to be the primary acoustic correlate of voicing in word-final position.
\citet{luce1985}, on the other hand, claim that vowel duration is a more robust cue to voicing across speaking rates, when compared to the CV ratio and the duration of the stop closure (which fared as the worst among the three indices).
Finally, \citet{ko2018} compares CV ratio values in three speaking styles (normal, faster, and slower) and finds that the ratio changes as a function of speaking style.
Moreover, the rate-driven differences in CV ratio differ in the voiceless and voiced condition.
In sum, while this would not be an argument against phonologisation of the voicing effect in English, there is contrasting evidence as to whether the relative magnitude of the effect is stable across speaking tempos.

<!-- add references from the meta-analysis -->
The alleged phonologisation of the effect in English is usually argued to be responsible for the greater effect in this language compared to others.
The reported effect of voicing in word-final syllables in English varies between 35 and 150 ms [add references].
When looking at non-final syllables, the effect is smaller, with values between 18 and 35 ms [add references].
Taking the first vowel in Italian disyllabic words for comparison, the difference in vowel duration before voiceless vs. voiced stops is 22 in \citet{farnetani1986} and 24 ms in \citet{esposito2002}.
These values are within the range of the non-final effect in English.
It is thus possible that, once controlling for contextual factors, the apparent cross-linguistic differences in magnitude get at least reduced.
A similar conclusion is proposed by \citet{laeufer1992}, who compared French and English with carefully designed material to ensure comparison.
When the duration of vowel is similar across languages, the magnitude of the effect is also comparable.
To conclude, there is mixed evidence as to whether there exist cross-linguistic differences in magnitude of the voicing effect, and arguments based on phonologisation of the effect as derived from stability across speaking rates should be taken with caution.

## Whence the voicing effect
\label{s:accounts}

Over a century of research on the voicing effect has without doubt increased our knowledge of this complex phenomenon.
However, to date no single proposal as to why this phenomenon exists has reached unanimous consensus.
The period between the 50s and the 70s generated a series of accounts about the source of the voicing effect, with subsequent decades focussing on testing or extending these hypotheses.
Two major 'factions' have opposing views regarding whether the effect originally emerged due to perceptual biases or physical properties of the production system.
At present, there is no ultimate answer as to which of the two sides best accounts for all of the aspects of the voicing effect, and rather both point of views partially contribute to the overall picture.
The following paragraphs will review the major perception and production accounts, with greater attention given to the latter, which are the focus of this dissertation.
<!-- this is not an in-depth nor exhaustive review -->
<!-- as in papers, doesn't exclude perception -->

<!-- Perception -->

One of the perception-based accounts states that the voicing effect emerges as a consequence of the difficulty in the perceptual identification of the vowel-consonant boundary in the context of voiced stops, and of the misinterpretation of the voicing during closure \citep{javkin1976}.
According to this account, speakers misperceive the periodic vibration of the vocal folds (voicing) during the closure of a voiced stop as part of the preceding vowel.
In the absence of contextual correction, this misperception can lead to the creation of a new production norm where the vowel is long.
If this new lexical representation is created, the listener, now turned speaker, will subsequently produce longer vowel durations when followed by voiced stops.
<!-- Ohala -->
Although \citet{javkin1976} does not directly test the hypothesis that closure voicing is reinterpreted as part of the preceding vowel, the results indicate that listeners perceive vowels to be longer when followed by voiced than when followed by voiceless stops, other things being equal.
On the other hand, \citet{sanker2019} finds that vowels rather elicit less 'long' responses when the consonant following the vowel is voiced, while they elicit more 'long' responses in stimuli where the following consonant is spliced out.
While there is potential for a perceptual bias driving some aspects of the voicing effect, production mechanisms of voiced stops affecting acoustic aspects of vowels could be at the root of perceptual biases, which could be responsible for the enhancement of the effect in some speakers/languages \citep{begus2017, sanke2019}.

To provide a rationale for the language-specificity of the voicing effect, \citet{kluender1988} propose that different languages can exploit the perceptual bias behind the effect at different degrees.
The ratio of the duration of the closure and that of the vowel is one of the perceptual cues to voicing \citet{port1982, lisker1986}.
Listeners associate smaller values of the consonant-to-vowel ratio to voiced stops, and, vice versa, greater values to voiceless stops.
\citet{kluender1988} argue that speakers can actively manipulate vowel durations to proportionally increase the difference in ratio between the two voicing categories, so that the ratio would be even smaller in the voiced context and even greater in the voiceless one.
As a consequence, the perceptual distance between the voicing categories would be enhanced, thus facilitating discrimination \citet{stevens1989, kingston1994}.
According to this view, listeners should show a contrast effect, by which longer closure durations elicit more 'short vowel' responses and shorter closures more 'long vowel' responses.
However, \citet{fowler1992} shows that listeners judge vowels to be longer when the stop closure duration is increased, and that, similarly, stop closure is perceived to be longer when vowel duration is increased.
These results indicate a mechanism of perceptual assimilation of the respective durations of vowels and stop closures, rather than a contrast effect which can be exploited in the enhancement of the voicing distinction.

<!-- Production -->

While individual production accounts differ in the details, two broad categories can be identified.
Two accounts ascribe the source of the voicing effect to some mechanisms of compensation within a certain property of speech (either duration or articulatory force), while two others relate the emergence of the effect to timing aspects of gestures related to the articulation of stops (either laryngeal or oral).

The compensatory temporal adjustment account \citep{lindblom1967, slis1969a, slis1969, lehiste1970, lehiste1970a} states that the relative durations of a vowel and consonant in a VC sequence are statistically correlated.
A well-known fact about stop closure is that it is longer in voiceless stops and shorter in voiced stops \citep{lisker1957, van-summers1987, davis1989, de-jong1991}.
As a consequence, vowels are shorter when followed by the longer closure of voiceless stops, and they are longer when followed by the shorter closure of voiced stops.
This compensatory pattern would be the consequence of maintaining a particular speech interval at a fixed temporal duration, while the duration of the closure changes depending on the voicing status of the stop.
Proponents of the compensatory account have argued that compensation is implemented either at the level of the syllable (or of the VC sequence, \citealt{lindblom1967, farnetani1986}), or at the level of the word \citep{slis1969a, slis1969, lehiste1970, lehiste1970a}.
This formulation of the account, however, faces empirical and logical challenges.
The duration of both the syllable and the word is affected by the voicing of the stop \citet{chen1970, jacewicz2009}, and it is not clear why compensation within a word should target the pre-consonantal vowel necessarily and not other segments (these issues will be discussed in more details in [...]).

A second proposal attributes the voicing-driven differential duration of vowels to articulatory energy expenditure, rather than temporal aspects.
\citet{meyer1903} and similarly \citet{belasco1953} propose that the articulatory force required to produce a syllable is constant, and thus it is distributed across segments according to their energy requirements.
According to this hypothesis, voiceless stops are produced with more force than voiced stops, and hence some force is subtracted from the production of the preceding vowel to maintaining the overall force constant.
However, the concept of 'articulatory force' lacks an empirically solid definition, and experimental results mentioned in \citet{zimmerman1958} rather point to the absence of a relation between energy expenditure and vowel duration.

While the compensatory temporal adjustment and the energy expenditure accounts rely on compensatory mechanisms of duration or articulatory force, two other proposals concern aspects of gestural timing of the larynx and the consonant closing gesture.
The laryngeal adjustment account \citet{halle1967, halle1967a, chomsky1968} is based on the idea that voicing during a stop closure requires precise adjustments of the glottis in order to comply with aerodynamic constraints \citep{ohala2011}.
Such a precision requires greater time to be achieved during articulation than the production of closure voicelessness, which requires a less precise control over glottal opening.
Because of these properties of laryngeal articulation, full closure can be achieved relatively faster in the context of voiceless stops, while a delay of closure onset in voiced stops ensures enough time to produce the suitable glottal configuration.
The preliminary electromiographic data of glottal muscular activity discussed in \citet{chen1970}, however, suggests that the expected early activity of laryngeal muscles during the production of vowels followed by voiced stops compared to vowels followed by voiceless stops is not found.
Further articulatory evidence shows that there is rather a general increase of activity of certain laryngeal muscles (mainly the posterior crycoarytenoid and the crycothyroid) during the production of voiceless sounds \citep{hirose1972, kagaya1975, hirose1977, lofqvist1989}.
No conclusive evidence can thus be adduced in support of the laryngeal adjustment hypothesis, although other laryngeal mechanisms cannot be ultimately excluded.

<!-- I think I need to read more about this -->

The last production account surveyed here is based on the rate of closure transition \citep{ohman1967a, chen1970}.
Voiceless stops are articulated with greater glottal opening relative to voiced stops (and vowels), so that a greater volume of air is admitted into the oral cavity.
@ohman1967a argues that the production of the closure of voiceless stops would then require more muscular effort to counteract the increased intra-oral pressure generated by the greater airflow.
As a consequence, the rate of the closing gesture of voiceless stops is higher than that of voiced stops.
In other words, full closure will be achieved earlier when the stop is voiceless than when it is voiced relative to the onset of the preceding vowel.
Hence, vowels will be shorter when followed by voiceless stops than when followed by voiced stops.
\citet{chen1970} observes from articulatory data of lip movements that the difference in labial closure rate accounted for 20% of the difference in vowel duration.
Subsequent work by \citet{warren2005} further shows that the percentage of difference accounted for rises to 80% when considering the movements of both the lips and the jaw.

<!-- to sum up -->

## Aspiration effect
<!-- and ejection effect? -->


Two phonation modes other than voicing are known to affect preceding vowel duration: aspiration and ejection.
While this project focusses on the voicing effect, the closely related aspiration and ejection effects have consequences of theoretical importance for the voicing effect.
The results concerning the aspiration effect are mixed.
\citet{maddieson1976}, \citet{durvasula2012}, and \citet{lampp2004} report longer vowels in aspirated than in unaspirated stops in Hindi, and \citet{maddieson1976a} a simlar trend in Assamese, Bengali, and Marathi.
\citet{ohala1992a}, on the other hand, shows that vowels have the same duration before unaspirated and aspirated stops in his sample of Hindi speakers.
\citet{sanker2018} observes an effect in Hindi long but not in short vowels, while the effect is reversed in Telugu long vowels (vowels are shorter before aspirated than unaspirated stops), with no appreciable difference in short vowels.
Note that these studies don't easily lend themselves to comparison, since the material and contexts used differ (vowel type, vowel phonological length, number of syllables, context following the test word).
An investigation of the effect of ejection in Georgian \citep{begus2017} shows that vowels are shortest when followed by aspirated stops, longer when followed by ejectives, and longest when followed by voiced stops (Georgian contrasts aspirated voiceless, ejective, and voiced unaspirated stops).

The trend of vowels being longer when followed by aspirated stops challenges some of the accounts presented in \Cref{s:accounts}, as noted in \citet{maddieson1976}.
The articulatory force expenditure hypothesis predicts vowels to be shorter before aspirated than before unaspirated stops since it is likely that aspirated stops require greater force than unaspirated ones.
According to the laryngeal adjustment account, the duration of the vowels should not differ in voiceless unaspirated and aspirated stops since they both require glottal opening, rather than the precise adjustments characteristic of voiced stops.
Since closure rate is determined by airflow, the rate of closure account expects vowels followed by aspirated stops to be shorter than or equal to vowels followed by unaspirated stops, since the former should be characterised by greater airflow and higher closure rates due to the spread glottis.
While \citet{maddieson1976} argue against a compensatory effect between vowel and consonant duration, the data in \citet{durvasula2012} are compatible with it (see [...] for details).
The results in \citet{sanker2018} on Hindi, but not Telugu, are also compatible with a compensatory mechanism.
Closure durations are longer in unaspirated stops and shorter in aspirated stops in both languages, but the effect of aspiration on vowel duration has opposite directions, as discussed above.
